In [5]:
from numpy import *
a = array([(1,2,3),(4,5,5)])
print(a)
print()

# print()
print(a.sum(axis=0))
print()
print(a.sum(axis=1))

[[1 2 3]
 [4 5 5]]

[5 7 8]

[ 6 14]


In [15]:
from numpy import *
a = array([(1,2,3),(4,5,6)])
b = array([(1,2,3),(4,5,6)])
print(a)
print()
print(hstack((a,b)))
# hstack() used for horizontal(row) stacking.
# it takes array name as arguments.
print()
print(vstack((a,b)))
# hstack() used for vertical(column) stacking.
# it takes array name as arguments.


[[1 2 3]
 [4 5 6]]

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [20]:
from numpy import *
a = array([(1,2,3),(4,5,6)])
print(a)
print()
print(a.ravel())
# ravel() fun is used to  change 2D dimension into 1D array.

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]
