In [1]:
print(4+4)

8


In [2]:
print("hello")

hello


In [3]:
from numpy import *
arr1 = array([1,2,3,4,5])
print(arr1)
print(log(arr1))
print(sqrt(arr1))
# print()
print(sum(arr1))
print(max(arr1))
print(min(arr1))
arr2= array([0,30,45,90])
print(sin(arr2))

[1 2 3 4 5]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[1.         1.41421356 1.73205081 2.         2.23606798]
15
5
1
[ 0.         -0.98803162  0.85090352  0.89399666]


In [4]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
# arr2= np.array([5])
arr2 = arr1;
print(arr2);
print(type(arr2))
print(arr2.dtype)
print(concatenate([arr1,arr2]))

[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
int32
[1 2 3 4 5 1 2 3 4 5]


In [5]:
# making 2D array
from numpy import *
# arr1= array([{1,2},{3,4}])
arr2= array([[1,2],[3,4]])
# print(arr1)
print(arr2)
# print(arr1.ndim)
print("the dimension of arr2 is:",arr2.ndim)
print("the no of rows and columns is:",arr2.shape)
print("the total no of elements is:",arr2.size)



[[1 2]
 [3 4]]
the dimension of arr2 is: 2
the no of rows and columns is: (2, 2)
the total no of elements is: 4
