In [12]:
from numpy import *
arr1 = array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
])
             
print(arr1)
print(arr1[2,2])
print("After converting 3D array into 1D array.")
arr2 = arr1.flatten()
# flatten() fun is used to change the dimension of the array.
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
After converting 3D array into 1D array.
[1 2 3 4 5 6 7 8 9]


In [10]:
# coverting a 1D array into 2D array.
from numpy import *
arr1 = array([1,2,3,4])
arr2 = arr1.reshape(2,2)
# reshape() fun is used to change 1D array into 2D or 3D array. 
# It takes no. of rows and columns as an argument.
print(arr2)

[[1 2]
 [3 4]]


In [4]:
print("hello")


hello


In [10]:
from numpy import *
arr1 = array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
print(arr1)
# convert an array in 3D array
arr2= arr1.reshape(2,2,3)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
from numpy import *
arr1 = zeros(5)
arr2 = ones(5)
arr3 = arange(1,10,2)
arr4 = linspace(1,3,10)
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 3 5 7 9]
[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [16]:
print("hello",end = " ")
print("World!")


hello World!
